### ISSUE TITLE
Show confirmation message after send button is clicked.

### ISSUE THREAD

**Issue by Ashwani132003** [Ashwani132003/Contact-Form#3]

**Comment by joe7898** [comment]
Hi, can I please be assigned this. Also, would you prefer this to be done using php or javascript and would you rather have an alert or a normal message under the form. Thanks

**Comment by Ashwani132003** [comment]
Ya, I will assign this to you Tomorrow 👍

**Comment by joe7898** [comment]
Hi, are you able to add a 'hacktoberfest-accepted' label so it will count. Thanks

**Comment by joe7898** [comment]
Hi, are you able to add a 'hactoberfest-accepted' label so it counts. Thanks

**Comment by Ashwani132003** [comment]
@joe7898  I added hactoberfest accepted label,
Now you will get update in some time

**Comment by joe7898** [comment]
Hi, it has just appeared on the hactoberfest website now but says it's still in progress

**Comment by Ashwani132003** [comment]
Everything is fine, it will get matured in 14days. No worries.
